package me.leoko.advancedban.network.protocol;

import java.util.Objects;
import java.util.UUID;

/**
 * Non-secret internal identity for a Paper Agent.
 *
 * <p>The UUID is generated by the Agent and may be persisted by the platform adapter. It is
 * authenticated as part of the handshake transcript, but it is not a credential and must never
 * be used as proof of network membership without the shared network key.</p>
 */
public final class AgentIdentity {
    private AgentIdentity() {
    }

    public static UUID generate() {
        return UUID.randomUUID();
    }

    /** Parses only the canonical UUID representation used on the wire. */
    public static UUID parse(String encoded) {
        Objects.requireNonNull(encoded, "encoded");
        UUID identity;
        try {
            identity = UUID.fromString(encoded);
        } catch (IllegalArgumentException exception) {
            throw new IllegalArgumentException("agent identity must be a UUID", exception);
        }
        if (!identity.toString().equals(encoded)) {
            throw new IllegalArgumentException("agent identity must use canonical UUID format");
        }
        if (identity.getMostSignificantBits() == 0L && identity.getLeastSignificantBits() == 0L) {
            throw new IllegalArgumentException("agent identity must not be the nil UUID");
        }
        return identity;
    }

    public static String encode(UUID identity) {
        return Objects.requireNonNull(identity, "identity").toString();
    }
}
